SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
GRID_SIZE = 20
GRID_WIDTH = SCREEN_WIDTH // GRID_SIZE
GRID_HEIGHT = SCREEN_HEIGHT // GRID_SIZE

SNAKE_SPEED = 10
SNAKE_SIZE = 20

FOOD_SIZE = 20

DEFAULT_BG_COLOR = (0, 0, 0)
DEFAULT_SNAKE_COLOR = (0, 255, 0)
DEFAULT_FOOD_COLOR = (255, 0, 0)

FONT_SIZE = 24
TITLE_FONT_SIZE = 48

DB_PATH = './data/snake_game.db'
SAVE_PATH = './data/saves/savedata_1.json'

DIRECTION_UP = (0, -1)
DIRECTION_DOWN = (0, 1)
DIRECTION_LEFT = (-1, 0)
DIRECTION_RIGHT = (1, 0)
